apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-pubsub-servicebus
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
    - name: connectionString # Used for local dev testing.
      value: "<sb-key>"
    - name: consumerID
      value: "sbts-tasks-processor"
scopes:
  - tm-backend-api
  - tm-backend-processor