trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - /apps/single/src/*
      - /.pipelines/code-deploy-aca.yml

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: imageRepository
    value: "single"
  - name: containerRegistry
    value: spacedevacr.azurecr.io
  - name: service_connection
    value: ARM_SERVICE_CONNECTION
  - name: containerAppName
    value: single-app
  - name: resource_group
    value: space-dev-platform
  - name: tag
    value: $[replace(variables['Build.BuildNumber'], '.', '-')]
  # - name: tag
  #   value: "20240708-9"
  - group: acr

stages:
  - stage: BuildAndDeploy
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            name: docker_build_and_push
            displayName: docker build and push
            inputs:
              containerRegistry: $(containerRegistry)
              repository: $(imageRepository)
              command: "buildAndPush"
              Dockerfile: "apps/single/src/Dockerfile"
              tags: |
                latest
                $(tag)-aca

      - job: Deploy
        dependsOn:
          - Build
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                pwd 
                sed -i 's/REVISIONSUFFIX/$(tag)-aca/g' .pipelines/single.yml
                sed -i 's/CONTAINERREGISTRY/$(containerRegistry)/g' .pipelines/single.yml
                sed -i 's/IMAGENAME/$(imageRepository)/g' .pipelines/single.yml
                sed -i 's/TAG/$(tag)-aca/g' .pipelines/single.yml
                sed -i 's/ACRPASSWORD/$(ACR_PASSWORD)/g' .pipelines/single.yml
              workingDirectory: $(System.DefaultWorkingDirectory)

          - task: CmdLine@2
            inputs:
              script: |
                pwd 
                cat .pipelines/single.yml
              workingDirectory: $(System.DefaultWorkingDirectory)
              #failOnStderr: false # boolean. Fail on Standard Error. Default: false.

          - task: AzureContainerApps@1
            # name: singleapp
            inputs:
              yamlConfigPath: "$(System.DefaultWorkingDirectory)/.pipelines/single.yml"
              # imageToDeploy: "$(containerRegistry)/$(imageRepository):$(tag)-aca"
              # acrName: "spacedevacr"
              azureSubscription: ${{variables.service_connection}}
              containerAppName: $(containerAppName)
              resourceGroup: $(resource_group)
              # acrUsername: $(ACR_USER_NAME)
              # acrPassword: $(ACR_PASSWORD)
              targetPort: 5000