trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - /src/*
      - /.pipelines/code-deploy-aca.yml

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: imageRepository
    value: "single"
  - name: containerRegistry
    value: spacedevacr.azurecr.io
  - name: service_connection
    value: ARM_SERVICE_CONNECTION
  - name: containerAppName
    value: single-apps
  - name: resource_group
    value: space-dev-platform
  # - name: tag
  #   value: "$(Build.BuildNumber)-aca"
  # - name: modttag
  #   value: $[replace(variables['Build.BuildNumber'], '.', '-')]
  - name: modttag
    value: "20240708-9"

  - group: acr

stages:
  - stage: BuildAndDeploy
    jobs:
      - job: Build
        steps:
          - task: CmdLine@2
            displayName: List and View
            inputs:
              script: |
                echo "Structure of work folder of this pipeline:"
                tree -a $(Build.SourcesDirectory)

          # - task: Docker@2
          #   name: docker_build_and_push
          #   displayName: docker build and push
          #   inputs:
          #     containerRegistry: $(containerRegistry)
          #     repository: $(imageRepository)
          #     command: "buildAndPush"
          #     Dockerfile: "apps/single/src/Dockerfile"
          #     tags: |
          #       latest
          #       $(modttag)-aca

      - job: Deploy
        dependsOn:
          - Build
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                pwd 
                # echo "$(tag)"
                # modtag=$(echo $tag | sed -e 's/\./-/g')
                # echo "$(modtag)"
                sed -i 's/REVISIONSUFFIX/$(modttag)-aca/g' .pipelines/single.yml
                sed -i 's/CONTAINERREGISTRY/$(containerRegistry)/g' .pipelines/single.yml
                sed -i 's/IMAGENAME/$(imageRepository)/g' .pipelines/single.yml
                sed -i 's/TAG/$(modttag)-aca/g' .pipelines/single.yml
                sed -i 's/ACRPASSWORD/$(ACR_PASSWORD)/g' .pipelines/single.yml
              workingDirectory: $(System.DefaultWorkingDirectory)

          - task: CmdLine@2
            inputs:
              script: |
                pwd 
                cat .pipelines/single.yml
              workingDirectory: $(System.DefaultWorkingDirectory)
              #failOnStderr: false # boolean. Fail on Standard Error. Default: false.

          - task: AzureContainerApps@1
            # name: singleapp
            inputs:
              yamlConfigPath: "$(System.DefaultWorkingDirectory)/.pipelines/single.yml"
              # imageToDeploy: "$(containerRegistry)/$(imageRepository):$(modttag)-aca"
              # acrName: "spacedevacr"
              azureSubscription: ${{variables.service_connection}}
              containerAppName: $(containerAppName)
              resourceGroup: $(resource_group)
              # acrUsername: $(ACR_USER_NAME)
              # acrPassword: $(ACR_PASSWORD)
              targetPort: 5000

          # - task: AzureContainerApps@1
          #   inputs:
          #     imageToDeploy: "$(containerRegistry)/$(imageRepository):$(tag)"
          #     azureSubscription: ${{variables.service_connection}}
          #     containerAppName: $(containerAppName_west)
          #     resourceGroup: $(resource_group)
          #     acrUsername: $(acrusername)
          #     acrPassword: $(acrpassword)
          #     targetPort: 5000

  # imageToDeploy: '$(containerRegistry)/$(imageRepository):latest'
  #  imageToDeploy: '$(containerRegistry)/$(imageRepository):$(Build.BuildId)'
  #TODO  - Try removing the Deploy Stage and see if the image pushed is automatically pulled by Web app ..
  # step 1 - makes some UI text change
  # step 2 - remove deploy stage
